Vue.jsを使ってToDoアプリを作成
R-Tsukada/vue-todo pull request #1
Opened 2021-11-04 13:58 UTC by R-Tsukada

Vue.jsの基本のプラクティスの課題を作成しました。

お忙しいとは思いますが、ご確認をお願いいたします🙇‍♂️

2021-11-09 15:30 UTC, komagata requested changes

2021-11-09 15:30 UTC, komagata commented on index.html
> +</html>
ファイル末尾に改行がないようです〜

2021-11-10 06:37 UTC, R-Tsukada commented on index.html
> +</html>
確認不足でした💦
末尾に改行を入れました！

2021-11-10 13:39 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-11-29 01:52 UTC, merged